name: squaad_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.4
  go_router: ^13.2.0
  http: ^1.2.1
  keep_screen_on: ^3.0.0
  shared_preferences: ^2.2.2
  video_player: ^2.7.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/SQUAAD.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#2C2C2C"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/schools/
    - assets/icons/
    - assets/videos/
